import Head from "next/head";
import Image from "next/image";
import React from "react";
import axios from "axios";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  try {
    const result = await axios.get(
      "https://api.tjori.com/api/v7filters/na/women-all-products/?f_page=290&format=json"
    );
    const data = result.data;
    return {
      props: {
        data: data,
      },
    };
  } catch (error) {
    console.log(error);
  }
}

export default function Home({ data }) {
  // console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>SHOP BAG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <marquee > */}
        <h1 className={styles.glow}> Welcome to the shopping card</h1>
        {/* </marquee> */}
      </div>
      {/* return ( */}
      <div className="container-fluid">
        {/* <h4>Access</h4> */}
        <div className="col-md-3  grid-container ">
          {data.data.products.map((currEle) => {
            return (
              <div className="grid-item" key={currEle.id}>
                <div className={styles.card2}>
                  <div className={styles.img}>
                    <img src={currEle.plpimaage} alt="product" />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      
     
    </div>
  )
};
